### ISSUE TITLE
Facing the new data set, how to retrain and inference?

### ISSUE THREAD

**Issue by Blue-Eagle-10** [ctom2/latent-space-transform#1]
@ctom2 
Thank you for sharing, it is very valuable!
May I ask:
1. If I apply your method to other fields, where do I need to modify this data set?
2. Can the training code be shared? I only saw the training of backbone CNN. If we face a new data set, do we need to retrain the later processing part? Do I just need to replace the corresponding data set?
Looking forward to your reply, thank you!

**Comment by ctom2** [comment]
You can apply the method to any images you want, there is no need for modifying the input data.

The method has no constraints on the backbone. If you want to use a different model for feature extraction you can pretrain it yourself on whatever dataset you want. For more details about the backbone training please refer to the repository linked in the description.
